# Generated by Django 4.2.1 on 2023-05-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_rpg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='story',
            name='characters_description',
        ),
        migrations.RemoveField(
            model_name='story',
            name='lore',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='story',
            name='world_context',
        ),
        migrations.RemoveField(
            model_name='story',
            name='world_rules',
        ),
    ]
