# Generated by Django 4.2.1 on 2023-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_rpg', '0002_remove_story_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.CharField(default=-3, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
