# Generated by Django 4.2.1 on 2023-06-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_rpg', '0003_story_description_alter_story_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.character')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.player')),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.story')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.player'),
        ),
        migrations.AddField(
            model_name='character',
            name='story_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.player'),
            preserve_default=False,
        ),
    ]
