# Generated by Django 4.2.1 on 2023-06-04 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_rpg', '0005_world_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.character')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.player')),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_rpg.story')),
            ],
        ),
    ]
